service: smart-next-step

provider:
  name: aws
  runtime: nodejs18.x
  region: ${env:AWS_REGION}
  stage: dev
  deploymentBucket:
    name: serverlessdeploymentbucket

plugins:
  - serverless-localstack

custom:
  localstack:
    host: http://localhost:${env:LOCALSTACK_EDGE_PORT}
    stages:
      - dev
    lambda:
      mountCode: true

functions:
  eventIngestion:
    handler: dist/lambdas/event-ingestion/handler.main
    environment:
      LOCALSTACK_EDGE_PORT: ${env:LOCALSTACK_EDGE_PORT}
      EVENT_TOPIC_ARN: ${env:EVENT_TOPIC_ARN}
    events:
      - http:
          path: events
          method: post

  recommendation:
    handler: dist/lambdas/recommendation/handler.main
    environment:
      LOCALSTACK_EDGE_PORT: ${env:LOCALSTACK_EDGE_PORT}
      RECOMMEND_TOPIC_ARN: ${env:RECOMMEND_TOPIC_ARN}
    events:
      - http:
          path: recommendations
          method: post

  vectorWorker:
    handler: lambdas/vector-worker/handler.main

build:
  esbuild: false 
