service: smart-next-step

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ${env:AWS_REGION}
  deploymentBucket:
    name: serverlessdeploymentbucket
  environment:
    LOCALSTACK_EDGE_PORT: ${env:LOCALSTACK_EDGE_PORT}
    EVENTS_TABLE: EventTable
    EVENT_TOPIC_NAME: eventTopic
    RECOMMEND_TOPIC_NAME: recommendationTopic
    QDRANT_URL: ${env:QDRANT_URL}
  lambdaHashingVersion: 20201221
  versionFunctions: false

plugins:
  - serverless-localstack

custom:
  localstack:
    host: http://localhost:${env:LOCALSTACK_EDGE_PORT}
    stages:
      - dev
    lambda:
      mountCode: true
      reuseContainers: true
      containerCleanup: true
    skipECR: true

functions:
  eventIngestion:
    handler: dist/lambdas/event-ingestion/handler.main
    environment:
      EVENT_TOPIC_NAME: eventTopic
    events:
      - http:
          path: events
          method: post

  recommendation:
    handler: dist/lambdas/recommendation/handler.main
    environment:
      RECOMMEND_TOPIC_NAME: recommendationTopic
    events:
      - http:
          path: recommendations
          method: get

  vectorWorker:
    handler: dist/lambdas/vector-worker/handler.main
    environment:
      QDRANT_URL: ${env:QDRANT_URL}
    events:
      - sns:
          topicName: eventTopic

  dynamoWorker:
    handler: dist/lambdas/dynamodb-worker/handler.main
    environment:
      EVENTS_TABLE: EventTable
    events:
      - sns:
          topicName: eventTopic

resources:
  Resources:
    EventTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: EventTable
        AttributeDefinitions:
          - AttributeName: companyId
            AttributeType: S
          - AttributeName: eventId
            AttributeType: S
        KeySchema:
          - AttributeName: companyId
            KeyType: HASH
          - AttributeName: eventId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST

    EventTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: eventTopic

    RecommendationTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: recommendationTopic