service: smart-next-step

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: ${env:AWS_REGION}
  deploymentBucket:
    name: serverlessdeploymentbucket
  environment:
    LOCALSTACK_EDGE_PORT: ${env:LOCALSTACK_EDGE_PORT}
    TOPICS_JSON: ${env:TOPICS_JSON}

plugins:
  - serverless-localstack

custom:
  localstack:
    host: http://localhost:${env:LOCALSTACK_EDGE_PORT}
    stages:
      - dev
    lambda:
      mountCode: true

functions:
  eventIngestion:
    handler: dist/lambdas/event-ingestion/handler.main
    environment:
      EVENT_TOPIC_ARN: ${env:eventTopic_ARN}
    events:
      - http:
          path: events
          method: post

  recommendation:
    handler: dist/lambdas/recommendation/handler.main
    environment:
      RECOMMEND_TOPIC_ARN: ${env:recommendationTopic_ARN}
    events:
      - http:
          path: recommendations
          method: get

  vectorWorker:
    handler: dist/lambdas/vector-worker/handler.main

resources:
  Resources:
    EventTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: EventTable
        AttributeDefinitions:
          - AttributeName: companyId
            AttributeType: S
          - AttributeName: eventId
            AttributeType: S
        KeySchema:
          - AttributeName: companyId
            KeyType: HASH
          - AttributeName: eventId
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST
